feat: Create scoped container that inherit a parent container's registrations
gbtb16/kiwi pull request #81
Opened 2022-05-08 10:43 UTC by ruicraveiro

Hi,

I am proposing this PR to add the only feature I am missing from Kiwi. It is the need to create a scoped container, but one that reuses all the parent's registrations. The idea is to emulate the feature I used in Unity in the past, http://unitycontainer.org/api/Unity.IUnityContainer.html#Unity_IUnityContainer_CreateChildContainer, but keeping Kiwi's existing API as unchanged as possible. 

The core of the PR is the scoped constructor, to which I added an optional parent parameter. When given a parent, the constructor will create a new _nameProviders map, which is essentially a deep clone of the parent's map:

```dart
  KiwiContainer.scoped([KiwiContainer? parent])
      : _namedProviders = parent == null
            ? Map<String?, Map<Type, _Provider<Object>>>()
            : parent._namedProviders
                .map((key, value) => MapEntry(key, {...value}));

```
The idea is for the scoped container to be a fork of the parent's registrations. After construction, all further modifications to the parent are not propagated to the scoped container. No modification to the scoped container should have an impact on the parent container. I added tests to check those behaviours.

Thank you for considering this PR.

Kind Regards,

Rui

2023-02-15 19:52 UTC, vanlooverenkoen requested changes

2023-02-15 19:52 UTC, vanlooverenkoen commented on kiwi/test/kiwi_test.dart
> +    // test('instances should be resolved', () {
do not keep commented tests

2023-02-15 19:52 UTC, vanlooverenkoen commented on kiwi/test/kiwi_test.dart
> -    test('KiwiContainer.scope should be a different object', () {
why did you remove this one? I would assume this test should still be working.

2023-02-15 19:53 UTC, vanlooverenkoen commented
Sorry for the long wait on the review. Forgot about this package, but I am back at it again.

2023-04-21 09:21 UTC, PhilipSA commented
@vanlooverenkoen Would love to have this but the original author seems to have forgotten about it. How could we proceed?

2023-04-21 09:29 UTC, vanlooverenkoen commented
@PhilipSA you could fork the repo that is linked to this pull request and I will review that. And close this one

2024-01-15 17:25 UTC, gbtb16 commented
Hi @ruicraveiro, your implementation was used as a basis in PR #98. I'm going to close this PR since the changes are already in the master. Thanks for your contribution!

2024-01-15 17:25 UTC, gbtb16 commented
Hi @ruicraveiro, your implementation was used as a basis in PR #98. I'm going to close this PR since the changes are already in the master. Thanks for your contribution!

2024-01-15 17:25 UTC, closed without merging